accounts/urls.py
from django.urls import path
from .views import (signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate, graphique, addresult, profile_eleve,
    multiplication, jeu ,verificationReponse, modal, soustraction, choixOperation, addition, multiplicationTable)

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('graphique/', graphique, name="graphique"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete"),
    path('multiplication/', multiplication, name="multiplication"),

    path('saveresult/', addresult, name="addresult"),
    #path('getdata/', getdata, name="getdata"),
    path('profile_eleve/', profile_eleve, name="profile_eleve"),
    #path('test_htmx/', test_htmx, name="test_htmx"),
    path('jeu/', jeu, name="jeu"),
    path('multiplicationTable/', multiplicationTable, name="multiplicationTable"),
    path('soustraction/', soustraction, name="soustraction"),
    path('addition/', addition, name="addition"),
    path('choixOperation/', choixOperation, name="choixOperation"),
    path('verificationReponse/', verificationReponse, name="verificationReponse"),
    path('modal/', modal, name="modal")
]

docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

accounts/models.py
import iso3166
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

from shop.models import SIZES, Color

# TYPE_USER = [("h", "Homme"), ("f", "Femme"), ("nr", "Non renseigné")]
TYPE_USER = [("h", "Homme"), ("f", "Femme")]


class ExChangerManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password, **kwargs):
        if not email:
            raise ValueError("email obligatoire")
        user = self.model(email=self.normalize_email(email), username=username, first_name=first_name,
                          last_name=last_name, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, first_name, last_name, password, **kwargs):
        user = self.create_user(email, username, first_name, last_name, password, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        return user


class ExChanger(AbstractUser):
    email = models.EmailField(unique=True)
    type = models.CharField(max_length=10, verbose_name="Sexe", choices=TYPE_USER)

    score_multiplication = models.IntegerField(default=0)
    score_addition = models.IntegerField(default=0)
    score_soustraction = models.IntegerField(default=0)
    score_division = models.IntegerField(default=0)

    #tablemultiplication_Niveau = models.IntegerField(default=1) #CREATION DE L'ATTRIBUT

    duree_connexion = models.IntegerField(default=0)

    a = models.IntegerField(default=0)
    b = models.IntegerField(default=0)
    answer = models.IntegerField(default=0)
    reponseEleve = models.FloatField(default=0)

    url = models.CharField(max_length=100, default=0)

    nombreQuestions = models.IntegerField(default=0)
    reponsesJustes = models.IntegerField(default=0)
    reponsesFausses = models.IntegerField(default=0)
    reponsesJustesPourcentage = models.FloatField(default=0)
    reponsesFaussesPourcentage = models.FloatField(default=0)

    tempsMoyenCentieme = models.FloatField(default=0)
    horaire1 = models.FloatField(default=0)
    #horaire2 = models.FloatField(default=0)
    Duree = models.FloatField(default=0)



    REQUIRED_FIELDS = ["username", "first_name", "last_name"]
    USERNAME_FIELD = "email"

    objects = ExChangerManager()

class Score(models.Model):
    user = models.OneToOneField(ExChanger, on_delete=models.CASCADE)
    multiplication = models.IntegerField(default=0)
    multiplicationNiveau = models.IntegerField(default=0)
    multiplicationALaSuite = models.IntegerField(default=0)
    multiplicationsFaussesALaSuite = models.IntegerField(default=0)


class Points(models.Model):
    user = models.OneToOneField(ExChanger, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    score1 = models.IntegerField(default=0)
    score2 = models.IntegerField(default=0)
    score3 = models.IntegerField(default=0)
    score4 = models.IntegerField(default=0)
    score5 = models.IntegerField(default=0)


class Meta:
    verbose_name="Point"

def __str__(self):
    return f"{self.user.username} à pour score : {self.score}"

class REPONSE(models.Model):
    name = models.CharField(max_length=255)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, forms
from captcha.fields import ReCaptchaField


class ExChangerSignupForm(UserCreationForm):
    captcha = ReCaptchaField()

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "first_name", "last_name", "type"]

accounts/views/password.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


class ExchangerChangePassword(PasswordChangeView):
    template_name = "password/change-form.html"
    success_url = reverse_lazy("accounts:change-done")


class ExchangerPasswordDone(PasswordChangeDoneView):
    template_name = "password/change-done.html"


class ExchangerResetPassword(PasswordResetView):
    template_name = "password/reset.html"
    success_url = reverse_lazy("accounts:reset-done")
    email_template_name = "password/reset-email.html"


class ExchangerResetDone(PasswordResetDoneView):
    template_name = "password/reset-done.html"


class ExchangerResetConfirm(PasswordResetConfirmView):
    template_name = "password/reset-confirm.html"
    success_url = reverse_lazy("accounts:reset-complete")


class ExchangerResetComplete(PasswordResetCompleteView):
    template_name = "password/reset-complete.html"

accounts/views/user.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from accounts.forms import ExChangerSignupForm

from verify_email.email_handler import send_verification_email

from accounts.models import Points

from random import *

from accounts.models import REPONSE

from time import time

from ..themes.Addition import Addition
from ..themes.TablesDeMultiplication import TablesDeMultiplication
from ..themes.Soustraction import Soustraction
from ..themes.ChoixOperation import ChoixOperation
from ..themes.VerificationReponse import VerificationReponse

from accounts.models import Score



def signup(request):
    if request.method == "POST":
        form = ExChangerSignupForm(request.POST)
        if form.is_valid():
            inactive_user = send_verification_email(request, form)
            Score.objects.create(user=inactive_user)
            return redirect("index")
        # Sans le else j'ai un formulaire vide si pas valide
    else:
        form = ExChangerSignupForm()
    return render(request, "accounts/signup.html", context={"form": form})


class ExChangerLogin(LoginView):
    template_name = "accounts/login.html"
    next_page = reverse_lazy("index")


def exchanger_logout(request):
    logout(request)
    return redirect("index")


@login_required
def exchanger_profile(request):
    user = request.user
    try:
        default_adresse = user.adresses.get(user=user, default=True)
    except ObjectDoesNotExist:
        default_adresse = None

    adresses = user.adresses.filter(user=user, default=False)

    return render(request, "accounts/profile.html", context={"user": user,
                                                             "default_adresse": default_adresse,
                                                             "adresses": adresses})

@login_required
def profile_eleve(request):
    user = request.user
    return render(request, "accounts/profile_eleve.html", context={"user": user})

class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = "accounts/update-profile.html"
    fields = ["email", "username", "first_name", "last_name"]
    success_url = reverse_lazy("accounts:profile_eleve")


def default_address_view(request, pk):
    user = request.user

    # current_address = user.adresses.get(user=user, default=True)
    # current_address.default = False
    # current_address.save()
    #
    # new_address = user.adresses.get(pk=pk)
    # new_address.default = True
    # new_address.save()
    # Mettre à jour l'adresse actuelle par défaut
    user.adresses.filter(default=True).update(default=False)

    # Définir la nouvelle adresse comme adresse par défaut
    updated_rows = user.adresses.filter(pk=pk).update(default=True)

    # Vérifier si l'adresse avec `pk=pk` a été mise à jour
    if not updated_rows:
        # Gérer l'erreur ici, par exemple en retournant une réponse d'erreur
        return HttpResponse("Adresse non trouvée", status=404)

    if request.GET.get("redirect") == "validate":
        return redirect("shop:address-choice")

    return redirect("accounts:profile")



#Test pour afficher le graphique
@login_required
def graphique(request):
    user = request.user
    return render(request, "accounts/graphique.html", context={"user": user})

@login_required
def multiplication(request):
    user = request.user
    return render(request, "accounts/multiplication.html", context={"user": user})

@login_required
def addresult(request):
    user = request.user
    tempsMoyenCentieme = request.POST.get('tempsMoyenCentieme')
    user.tempsMoyenCentieme = tempsMoyenCentieme
    user.save(update_fields=['tempsMoyenCentieme'])
    return redirect("accounts:modal")

@login_required
def jeu(request):
    user = request.user
    user.nombreQuestions = 0
    user.reponsesJustes = 0
    user.reponsesFausses = 0
    user.reponsesJustesPourcentage = 0
    user.reponsesFaussesPourcentage = 0
    user.Duree = 0
    user.save(update_fields=['nombreQuestions', 'reponsesJustes', 'reponsesFausses', 'reponsesJustesPourcentage', 'reponsesFaussesPourcentage', 'Duree'])
    # INITIALISATION DES QUESTIONS A LA SUITE
    user.score.multiplicationALaSuite = 0
    user.score.save(update_fields=['multiplicationALaSuite'])

    if request.method == "POST":
        if form.is_valid():
            print(form.cleaned_data)
    return render(request, "accounts/jeu.html", context={"user": user})

@login_required
def choixOperation(request):
    user = request.user
   # tableauOperation = ["accounts:test_htmx","accounts:soustraction"]
    #indice = randint(0, 1)
    #url_operation = tableauOperation[indice]
    #return render(request, "accounts/choixOperation.html", context={"url_operation": url_operation })
    url, a, b, answer = ChoixOperation(user)
    return render(request, url, context={"user": user, "a": a, "b": b, "answer": answer})



@login_required
def multiplicationTable(request):
    user = request.user
    #user = request
    a,b,answer = TablesDeMultiplication(user)
    #return render(request, "accounts/multiplicationTable.html", context={"user": user, "a": a, "b": b, "answer":answer})
    return render(request, "accounts/multiplicationTableAlenvers.html", context={"user": user, "a": a, "b": b, "answer": answer})




@login_required
def soustraction(request):
    user = request.user
    a,b = Soustraction(request.user)
    return render(request, "accounts/soustraction.html", context={"user": user, "a": a, "b": b})

def addition(request):
    user = request.user
    a,b = Addition(request.user)
    return render(request, "accounts/addition.html", context={"user": user, "a": a, "b": b})

@login_required
def verificationReponse(request):
    user = request.user
    user.reponseEleve = int(request.POST.get('name'))
    user.save(update_fields=['reponseEleve'])
    return HttpResponse(VerificationReponse(user))

    """
    answer = request.user.answer

    user.nombreQuestions +=1
    user.save(update_fields=['nombreQuestions'])

    horaire2 = time()

    duree = horaire2 - request.user.horaire1
    request.user.Duree = request.user.Duree + duree
    user.save(update_fields=['Duree'])

    html_response_nbre_questions ="<h6 id='hid_nombreQuestions'>Nombre de Question(s) : %s</h6>"

    if reponse == request.user.answer:
        user.reponsesJustes +=1
        user.save(update_fields=['reponsesJustes'])
        user.reponsesJustesPourcentage = round((user.reponsesJustes / user.nombreQuestions) * 100, 1);
        user.reponsesFaussesPourcentage = round((user.reponsesFausses / user.nombreQuestions) * 100, 1);
        user.save(update_fields=['reponsesJustesPourcentage', 'reponsesFaussesPourcentage'])

        if user.score.multiplication == 1:
            user.score.multiplicationALaSuite +=1
            user.score.save(update_fields=['multiplicationALaSuite'])
            if user.score.multiplicationALaSuite == 5:
                if user.score.multiplicationNiveau != 4:
                    user.score.multiplicationNiveau +=1
                    user.score.save(update_fields=['multiplicationNiveau'])
                    user.score.multiplication = 0
                    user.score.save(update_fields=['multiplication'])



        html_response = ("<h2>Bravo, c'est la bonne réponse</h2><input class='form-control-lg w-100 h-100 vrai' type='number' name='name' value='' disabled  style='font-size:30px; text-align:center;' id='hid_inp' placeholder=%s>" % answer)
        html_response_reponses_justes ="<h6 id='hid_resultatsJustes'>Réponse(s) Juste(s) : %s </h6>"
        return HttpResponse(html_response + html_response_reponses_justes % user.reponsesJustes + html_response_nbre_questions % user.nombreQuestions)

    else :
        user.reponsesFausses +=1
        user.save(update_fields=['reponsesFausses'])
        user.reponsesJustesPourcentage = round((user.reponsesJustes / user.nombreQuestions) * 100, 1);
        user.reponsesFaussesPourcentage = round((user.reponsesFausses / user.nombreQuestions) * 100, 1);
        user.save(update_fields=['reponsesJustesPourcentage', 'reponsesFaussesPourcentage'])

        if user.score.multiplication == 1:
            user.score.multiplicationALaSuite = 0
            user.score.save(update_fields=['multiplicationALaSuite'])
            user.score.multiplication = 0
            user.score.save(update_fields=['multiplication'])

        html_response1 = "<h2 class='text-danger'>Faux, la bonne réponse est %s</h2>"
        html_response2 = "<input class='form-control-lg w-100 h-100 faux' type='number' name='name' value='' disabled style='font-size:30px; text-align:center;' id='hid_inp' placeholder=%s>"
        html_response_reponses_fausses = "<h6 id='hid_resultatsFaux'> Réponse(s) Fausse(s) : %s </h6>"
        return HttpResponse(html_response1 % answer + html_response2 % reponse + html_response_reponses_fausses % user.reponsesFausses + html_response_nbre_questions % user.nombreQuestions)
    """

@login_required
def modal(request):
    user = request.user
    dureeMoyenDuJeu = round(request.user.Duree/request.user.nombreQuestions,1)
    return render(request, "accounts/modal.html", context={ "user": user, "dureeMoyenDuJeu":dureeMoyenDuJeu})

accounts/templates/accounts/create-address.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Créer une adresse{% endblock %}


{% block body %}
<div class="row">
    <div class="col">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Envoyer" class="btn btn-outline-primary">

        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/graphique.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}graphique{% endblock %}

{% block body %}

<!--<!DOCTYPE html> -->
<html lang="fr" xmlns:padding-left="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <title>Graphique radar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/stylecalc.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
<div class="container-fluid">
    <!--<div class="row">

        <div class="col bg-warning text-black">
            <div class="text-center">
                <br>
                <br>
                <div class="card mx-auto mb-5" style="width: 18rem;">
                    <div class="card-header"> Profil </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Email : {{ user.email }}</li>
                        <li class="list-group-item">Pseudo : {{ user.username }}</li>
                        <li class="list-group-item">Nom : {{ user.first_name }}</li>
                        <li class="list-group-item">Prénom : {{ user.last_name }}</li>
                    </ul>
                </div>
                    <a href="{% url 'accounts:profile-update' pk=user.pk %}" class="btn btn-outline-primary">Mettre à jour mes
                     informations</a>
                    <br>
                    <br>
                    <a href="{% url 'accounts:change-password' %}" class="btn btn-primary text-light">Modifier mon mot de passe</a>
             </div>

        </div>
    </div>-->
        <h2 class="pb-3" style="text-align:center">Classements</h2>

        <div class="row align-items-center">
            <div class="col-6 mx-auto mb-5" style="width: 23rem;">
                   <ul class="list-group">
                       <li class="list-group-item list-group-item-primary">Plus grand nombre de bonnes réponses</li>
                       <li class="list-group-item indentation">1er : {{ user.email }}</li>
                       <li class="list-group-item indentation">2e : {{ user.username }}</li>
                       <li class="list-group-item indentation">3e : {{ user.first_name }}</li>
                   </ul>
            </div>

            <div class="col-6 mx-auto mb-5" style="width: 23rem;">
                   <ul class="list-group">
                       <li class="list-group-item list-group-item-primary">Les plus rapides</li>
                       <li class="list-group-item indentation">1er : {{ user.email }}</li>
                       <li class="list-group-item indentation">2e : {{ user.username }}</li>
                       <li class="list-group-item indentation">3e : {{ user.first_name }}</li>
                   </ul>
            </div>

            <div class="col-6 mx-auto mb-5" style="width: 23rem;">
                   <ul class="list-group">
                       <li class="list-group-item list-group-item-primary">Meilleurs combos</li>
                       <li class="list-group-item indentation">1er : {{ user.email }}</li>
                       <li class="list-group-item indentation">2e : {{ user.username }}</li>
                       <li class="list-group-item indentation">3e : {{ user.first_name }}</li>
                   </ul>
            </div>
        </div>

        <h2 class="pt-3" style="text-align:center">Mes Compétences</h2>
        <div class="col bg-transparent text-black" style = "text-align:center">
                <div class="mx-auto" style="width: 75%">
                    <canvas id="myChart" width="0" display="block"></canvas>
                </div>
        </div>

</div>

<!-- Configuration Global du graphique radar -->
<script>
    /*Chart.defaults.plugins.title.display = true;
    Chart.defaults.plugins.title.text = "Mes Compétences";
    Chart.defaults.font.size = 20;*/
</script>

<script>
  const ctx = document.getElementById('myChart');
  new Chart(ctx, {

    type: 'radar',

    data: {
      labels: ['score1', 'score2', 'score3', 'score4', 'score5'],
      datasets: [{
        label: '',
        data: [{{ user.points.score1 }}, {{ user.points.score2 }}, {{ user.points.score3 }}, {{ user.points.score4 }}, {{ user.points.score5 }}],
        /*fill:true,*/
        borderWidth: 1
      }]
    },

    options: {
        plugins: {
            title: {
                <!-- text:'', -->
                padding: {
                            top:0,
                            bottom:0
                },
                font: {
                    size: 26
                }
           },

           subtitle: {
                text: 'Custom Chart Subtitle',
           },
        },


        scales: {
            r: {
                beginAtZero: true,
                max:100,
                pointLabels: {
                    color: 'black',
                    font: {
                        size: 26
                    }
                }
            }
        }


    }
  });
</script>
</body>
</html>

{% endblock %}

accounts/templates/accounts/inscription.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Inscription{% endblock %}


{% block body %}

<div class="row align-items-center">
    <div class="col-6 align-self-center">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-center">Inscription individuelle</h5>
                <!--<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
            </div>
            <a href="{% url 'accounts:signup' %}"><img src="{% static 'assets/eleve_seul.jpg' %}" class="card-img-bottom"></a>
        </div>
    </div>

    <div class="col-6 align-self-center">
        <div class="text-center">
            <div class="card">
                 <div class="card-body">
                    <h5 class="card-title text-center">Inscription par classe</h5>
                    <!--<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
                </div>
                 <a href="{% url 'accounts:signup_classe' %}"><img src="{% static 'assets/eleves_classe.jpg' %}" class="card-img-bottom"></a>
            </div>
        </div>
    </div>
</div>
<div class="row p-5">

</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}


{% block body %}


<div class="row">
    <div class="col-6">
        <form method="post" class="mb-5">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Envoyer" class="btn btn-outline-primary">

        </form>

        <a href="{% url 'accounts:reset' %}" class="btn btn-danger">Demander un nouveau mot de passe</a>
    </div>
    <div class="col-6">
<div class="text-center">
<img src="{% static 'assets/signup_compress.jpg' %}" class="img-fluid">
</div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/modal.html
{% load static %}

	<div class="modal-dialog modal-dialog-centered">
  		<div class="modal-content">
			<div class="modal-header bg-primary bg-opacity-50 text-light">
				<h5 class="modal-title">En cours d'enregistrement...</h5>
			</div>
			<div class="modal-body">
                <p id="hid_modale_nombre_questions">Aujourd'hui, sur {{ user.nombreQuestions }} question(s) : </p>
                <p class="indentation" id="hid_modale_resultats_justes"> {{ user.reponsesJustesPourcentage }}% de réponses justes.</p>
                <p class="indentation" id="hid_modale_resultats_faux"> {{ user.reponsesFaussesPourcentage }}% de réponses fausses.</p>
                <p class="indentation" id="hid_modale_temps"> Temps moyen pour répondre : {{ dureeMoyenDuJeu }} s.</p>
            </div>
			<div class="modal-footer">
				<button onclick="window.location.href = 'http://127.0.0.1:8000';" type="button" class="btn btn-primary" data-bs-dismiss="modal">Quitter</button>
				<!--<button onclick="window.location.href = '/account/graphique/';" type="button" class="btn btn-primary" data-bs-dismiss="modal">Quitter</button>-->
				<!--<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Quitter</button>-->
			</div>
  		</div>
	</div>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Profil{% endblock %}


{% block body %}
<div class="row">
    <div class="col-4">

        <div class="text-center">
            <div class="card mx-auto mb-5" style="width: 18rem;">
                <div class="card-header">
                    Profil
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Email : {{ user.email }}</li>
                    <li class="list-group-item">Pseudo : {{ user.username }}</li>
                    <li class="list-group-item">Nom : {{ user.first_name }}</li>
                    <!--<li class="list-group-item">Prénom : {{ user.last_name }}</li>
                    <li class="list-group-item">Taille Haut : {{ user.upper_size_property }}</li>
                    <li class="list-group-item">Taille Bas : {{ user.lower_size_property }}</li>
                    <li class="list-group-item">Pointure : {{ user.foot_size_property }}</li>
                    <li class="list-group-item">Couleur favorite : {{ user.favorite_color_property }}</li> -->
                </ul>
            </div>
            <a href="{% url 'accounts:profile-update' pk=user.pk %}" class="btn btn-outline-success">Mettre à jour mes informations</a>
        </div>


    </div>

<!--

    <div class="col-4">

        <div class="text-center">
            {% if default_adresse %}
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    Adresse par défaut
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ default_adresse.name }}</li>
                    <li class="list-group-item">{{ default_adresse.address_1 }}</li>
                    {% if default_adresse.address_2 %}
                    <li class="list-group-item">{{ default_adresse.address_2 }}</li>
                    {% endif %}
                    <li class="list-group-item">{{ default_adresse.zip_code }} - {{ default_adresse.city }}</li>
                    <li class="list-group-item">{{ default_adresse.get_country_display }}</li>
                </ul>
            </div>


            {% else %}
            Pas d'adresse(s) enregistrées
            {% endif %}


        </div>

    </div>




    <div class="col-4">

        <div class="text-center">
            <a href="{% url 'accounts:change-password' %}" class="btn btn-danger">Modifier son mot de passe</a>


        </div>

    </div>

</div>

<div class="row" style="margin-top: 20px;">

    <div class="col">

        <div class="text-center">
            <p class="d-inline-flex gap-1">
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Autres adresses
                </button>
            </p>
            <div class="collapse" id="collapseExample">
                {% for adresse in adresses %}
                <div class="card card-body mx-auto" style="margin-bottom: 20px; max-width: 300px;">

                    Toutes les adresses False



                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ adresse.name }}</li>
                        <li class="list-group-item">{{ adresse.address_1 }}</li>
                        {% if adresse.address_2 %}
                        <li class="list-group-item">{{ adresse.address_2 }}</li>
                        {% endif %}
                        <li class="list-group-item">{{ adresse.zip_code }} - {{ default_adresse.city }}</li>
                        <li class="list-group-item">{{ adresse.get_country_display }}</li>
                    </ul>

                    <form action="{% url 'accounts:default_address' pk=adresse.pk %}" method="post">

                        {% csrf_token %}
                        <input type="submit" value="Définir" class="btn btn-outline-info">

                    </form>


                </div>
                {% endfor %}
            </div>

        </div>

    </div> -->


</div>
{% endblock %}