accounts/urls.py
from django.urls import path
from .views import (signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate, graphique, addresult, profile_eleve,
    multiplication, jeu ,verificationReponse, modal, soustraction, choixOperation, addition, multiplicationTable)

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('graphique/', graphique, name="graphique"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete"),
    path('multiplication/', multiplication, name="multiplication"),

    path('saveresult/', addresult, name="addresult"),
    #path('getdata/', getdata, name="getdata"),
    path('profile_eleve/', profile_eleve, name="profile_eleve"),
    #path('test_htmx/', test_htmx, name="test_htmx"),
    path('jeu/', jeu, name="jeu"),
    path('multiplicationTable/', multiplicationTable, name="multiplicationTable"),
    path('soustraction/', soustraction, name="soustraction"),
    path('addition/', addition, name="addition"),
    path('choixOperation/', choixOperation, name="choixOperation"),
    path('verificationReponse/', verificationReponse, name="verificationReponse"),
    path('modal/', modal, name="modal")
]

docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

shop/urls.py
from django.urls import path


from .views import detail_view, add_to_cart, cart_view, delete_garments_cart, delete_cart, CreateGarment, all_garments, \
    DeleteGarment, my_shop_view, validate_cart, address_choice_view, admin_deal_validation_view, recommendations_view, \
    admin_advert_validation_view

app_name = "shop"
urlpatterns = [
    path("garment/<str:slug>/<int:pk>/", detail_view, name="detail"),
    path("add-to-cart/<int:pk>/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("address-choice/", address_choice_view, name="address-choice"),
    path("validate-cart/", validate_cart, name="validate-cart"),
    path("delete-garments/", delete_garments_cart, name="delete-garments"),
    path("delete-cart/", delete_cart, name="delete-cart"),
    path("create-garment/", CreateGarment.as_view(), name="create"),
    path("delete-garment/<int:pk>/", DeleteGarment.as_view(), name="delete-garment"),
    path("all/", all_garments, name="all"),
    path("recommendations/", recommendations_view, name="recommendations"),
    path("my-shop/", my_shop_view, name="my-shop"),
    path("admin-validation/", admin_deal_validation_view, name="admin-validation"),
    path("admin-ad-validation/", admin_advert_validation_view, name="admin-advert"),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <!--<link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>-->
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/stylecalc.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/class-tools.js"></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/disable-element.js"></script>

        <!--RAJOUTTTER POUR AVOIR LE MEME MENU

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
    <link rel="stylesheet" href="{% static 'css/styleAccueil.css' %}">
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/styleAccueilBis.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>


<body>

<!--NOUVELLE BAR DE NAVIGATION-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-opacity-100">
<!--<nav class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark shadow">-->
    <div class="container py-auto px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'index' %}">Calcul mental et automatismes</a>

        <!--Menu burger pour les smartphone-->
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-content"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-content">

        <!-- MENUS DE GAUCHE-->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

         <!-- MENU JOUER ET STATISTIQUES-->
          {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:jeu' %}">S'entraîner</a></li>
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:graphique' %}">Statistiques</a></li>

            {% endif %}
         <!-- FIN JOUER ET STATISTIQUES-->

         <!-- MENU TECHNIQUES-->
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown" data-bs-auto-close="outside">Techniques</a>
            <ul class="dropdown-menu shadow">
              <!--<li><a class="dropdown-item" href="#">Gallery</a></li>-->

              <li><a class="dropdown-item" href="#">Cerveau et Mémoires</a></li>
              <li><hr class="dropdown-divider"></li>
              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Automatismes</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href=""> Les Tables de Multiplication 0 ; 1 ; 2 ; 3 et 5</a></li>
                  <li><a class="dropdown-item" href=""> Les Tables de Multiplication 4 ; 6 ; 7 ; 8 et 9</a></li>
                </ul>
              </li>

              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Procédures niveau 1</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href="{% url 'shop:all' %}">Les additions</a></li>
                  <li><a class="dropdown-item" href="{% url 'shop:all' %}">Les soustractions</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 1</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 2</a></li>
                </ul>
              </li>

              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Procédures niveau 2</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href=""> Exemple 1</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 2</a></li>
                </ul>
              </li>

              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Procédures niveau 3</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href=""> Exemple 1</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 2</a></li>
                </ul>
              </li>
            </ul>
          </li>
         <!--FIN TECHNIQUES-->

         <!--NOUS CONTACTER -->
             <li class="nav-item dropdown">
                <a class="nav-link active dropdown-toggle" id="navbarDropdown30" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Nous Contacter</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown30">
                    <li><a class="dropdown-item" href="{% url 'sav:new-ticket' %}">Envoyer un message</a></li>
                    <li><hr class="dropdown-divider"/></li>
                    <li><a class="dropdown-item" href="{% url 'sav:pending-tickets' %}">Messages en cours</a></li>
                    <li><a class="dropdown-item" href="{% url 'sav:closed-tickets' %}">Historique</a></li>
                </ul>
            </li>
         <!-- FIN NOUS CONTACTER-->

        </ul>

        <!-- LIENS POUR ADMIN SEULEUMENT -->
                {% if request.user.is_superuser %}
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" id="navbarDropdown40" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Tâches en attente</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown40">
                        <li><a class="dropdown-item" href="{% url 'shop:admin-validation' %}">Echanges en attente</a></li>
                        <li><a class="dropdown-item" href="{% url 'shop:admin-advert' %}">Annonces en attente</a></li>
                        <li><a class="dropdown-item" href="{% url 'sav:admin-tickets' %}">Tickets en attente</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Administration</a></li>
                {% endif %}
        <!-- FIN LIENS ADMIN -->


        <!-- BARRE DE NAVIGATION DEUXIEME PARTIE A DROITE -->
            <ul class="navbar-nav  ml-auto mb-2 mb-lg-0 ms-lg-4 ml-auto">
                 <!-- Deconnexion Inscription Connexion-->
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:profile_eleve' %}">Profil</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Déconnexion</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Inscription</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Connexion</a></li>
                {% endif %}
                <!-- Fin Deconnexion Inscription Connexion-->
           </ul>
        <!-- FIN BARRE DE NAVIGATION A DROITE-->

      </div>
    </div>
  </nav>
<!-- FIN NOUVELLE BAR DE NAVIGATION-->




<!-- Header-->
<!--<header class="bg-light bg-gradient py-5 border border-secondary">-->
<header class="bg-white py-4">
    <div class="container px-4 px-lg-5 my-2">
        <div class="text-center text-black">
            <h1 class="display-4 fw-bolder text-color:primary text-primary opacity-50">Calcul mental et Automatismes</h1>
            <p class="lead fw-normal text-black-50 mb-0 text-secondary">Site pour s'entraîner et progresser</p>
        </div>
    </div>
</header>


        {% block body %}
        {% endblock %}




<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>




<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small class="text-white">Copyright &copy; Calcul Mental et Automatismes 2024</small>
    </div>
</footer>


</body>
</html>

templates/base_shop.html
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..."/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Fancy Product</h5>
                            <!-- Product price-->
                            $40.00 - $80.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>